---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
        - name: result-container
          image: sjagtap0/result
          ports:
            - containerPort: 80
          env:
            - name: PG_HOST
              value: "postgres-service"
            # - name: POSTGRES_USER
            #   valueFrom:
            #     secretKeyRef:
            #       name: db-credentials
            #       key: POSTGRES_USER
            # - name: POSTGRES_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: db-credentials
            #       key: POSTGRES_PASSWORD
            - name : PG_USER
              value : "postgres"
            - name : PG_PASSWORD
              value: "postgres"
            - name: PG_PORT
              value: "5432"
            - name: PG_DATABASE
              value: "votes"
---
apiVersion: v1
kind: Service
metadata:
  name: result-service
spec:
  selector:
    app: result
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
