name: CI/CD Pipeline
run-name: ${{ github.actor }} is Deploying

on:
  push:
    branches: 
      - main
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-test-and-docker:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Build Docker images
#         run: |
# #          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/vote:latest delpoy_voting_app_EKS_cluster/vote
#            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/worker:latest delpoy_voting_app_EKS_cluster/worker
#            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/result:latest delpoy_voting_app_EKS_cluster/result

      - name: Build Docker images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/result:latest delpoy_voting_app_EKS_cluster/result


      # - name: Push Docker images
      #   run: |
      #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/vote:latest
      #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/worker:latest
      #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/result:latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install kubectl
        run: |
          curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.32.0/2024-12-20/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.AWS_CLUSTER }}

      - name: Generate the final deployment template
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext-base
          export VOTE_NAME="docker.io/${{ secrets.DOCKERHUB_USERNAME }}/voting_app:${{ env.IMAGE_TAG }}"
          envsubst < vote_deployment_svc.yaml > vote_deployment_svc.yaml

          export RESULT_NAME="docker.io/${{ secrets.DOCKERHUB_USERNAME }}/result_app:${{ env.IMAGE_TAG }}"
          envsubst < result_deployment_svc.yaml > vote_deployment_svc.yaml

          export VOTE_NAME="docker.io/${{ secrets.DOCKERHUB_USERNAME }}/worker-app:${{ env.IMAGE_TAG }}"
          envsubst < worker_deployment_svc.yaml > worker_deployment_svc.yaml


          echo "Final deployment:"
          cat vote_deployment_svc.yaml

      - name: Deploy to EKS
        run: |
          kubectl apply -f .
